name: CI

on: [push, pull_request]

jobs:
  test:
    name: Build, test and push new docker image
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          cache: maven

      - name: Build and test
        run: mvn --batch-mode --update-snapshots verify

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_USER_PASSWORD }}

      - name: Build docker image
        run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=${{ secrets.DOCKERHUB_USER_NAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:latest

      - name: Publish docker image
        run: docker push ${{ secrets.DOCKERHUB_USER_NAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}:latest